volumes:
  poetry-cache:

services:
  statsboards-backend-test:
    labels:
      logging: "promtail"
      logging_jobname: "backend_test_logs"
    image: statsboards-backend-test:latest
    container_name: statsboards-backend-test-container
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest -v
#    command: pytest tests/test_db_services/test_season_service.py::TestSeasonServiceDB::test_get_tournaments_by_season_id_and_sport_id -v
    volumes:
      - poetry-cache:/root/.cache/pypoetry  # Add Poetry cache volume
    env_file:
      - .env.test.in.docker
    depends_on:
      - postgres_test

  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"