volumes:
  poetry-cache:

services:
  statsboards-backend:
    labels:
      logging: "promtail"
      logging_jobname: "backend_dev_logs"
    image: statsboards-backend-dev:latest
    container_name: statsboards-backend-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: poetry run python runserver.py
    ports:
      - "9000:9000"
    env_file:
      - .env.dev
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - poetry-cache:/root/.cache/pypoetry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
