version: '3'
services:
  statsboards-backend:
    container_name: statsboards-backend-dev-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: poetry run python runserver.py
    ports:
      - "9000:9000"
    env_file:
      - .env.dev