# Use the official Python 3.12 base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Copy the project files
COPY pyproject.toml poetry.lock ./
COPY . /app

# Configure Poetry to avoid creating a virtual environment
RUN poetry config virtualenvs.create false

# Install test dependencies
RUN poetry install --with test --no-interaction --no-ansi

# Use environment variables from the .env file
ENV PYTHONUNBUFFERED=1

# Default command is pytest
CMD ["pytest", "tests/test_db_services/test_season_service.py::TestSeasonServiceDB::test_get_tournaments_by_season_id_and_sport_id -v"]