"""Create matches table

Revision ID: 74d590a27d8c
Revises: 6ae0f074ec19
Create Date: 2023-12-10 18:08:44.222345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74d590a27d8c"
down_revision: Union[str, None] = "6ae0f074ec19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "match_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column("match_date", postgresql.TIME(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
