"""Update scoreboard table

Revision ID: 7d8ef0402236
Revises: 62c87578ed6a
Create Date: 2023-12-12 12:16:17.178818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d8ef0402236"
down_revision: Union[str, None] = "62c87578ed6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoreboard",
        sa.Column("is_qtr", sa.Boolean(), nullable=False),
        sa.Column("is_time", sa.Boolean(), nullable=False),
        sa.Column("is_playclock", sa.Boolean(), nullable=False),
        sa.Column("is_downdistance", sa.Boolean(), nullable=False),
        sa.Column(
            "team_a_color",
            sa.String(length=10),
            server_default="#c01c28",
            nullable=False,
        ),
        sa.Column(
            "team_b_color",
            sa.String(length=10),
            server_default="#1c71d8",
            nullable=False,
        ),
        sa.Column("match_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scoreboard")
    # ### end Alembic commands ###
