"""Create one_to_many tournaments table

Revision ID: c5327b7d034d
Revises: 912aa2bd784a
Create Date: 2023-12-05 20:38:41.891103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5327b7d034d"
down_revision: Union[str, None] = "912aa2bd784a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tournament_season_id_key", "tournament", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("tournament_season_id_key", "tournament", ["season_id"])
    # ### end Alembic commands ###
