"""Create teams_tournament table refactor

Revision ID: 7b7ede01e131
Revises: f3fb2ee4db22
Create Date: 2023-12-09 10:48:53.693129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b7ede01e131"
down_revision: Union[str, None] = "f3fb2ee4db22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "idx_unique_team_tournament", "team_tournament", ["tournament_id", "team_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idx_unique_team_tournament", "team_tournament", type_="unique")
    # ### end Alembic commands ###
