"""Create matchdata table

Revision ID: 14ca3c12162d
Revises: 87bb70e9bbb1
Create Date: 2023-12-11 10:46:09.475900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14ca3c12162d"
down_revision: Union[str, None] = "87bb70e9bbb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchdata",
        sa.Column("score_team_a", sa.Integer(), nullable=True),
        sa.Column("score_team_b", sa.Integer(), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchdata")
    # ### end Alembic commands ###
