"""Create teams table

Revision ID: a18973f3d92c
Revises: c5327b7d034d
Create Date: 2023-12-06 13:12:28.749077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a18973f3d92c"
down_revision: Union[str, None] = "c5327b7d034d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team",
        sa.Column("team_eesl_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=True),
        sa.Column("team_logo_url", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_eesl_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team")
    # ### end Alembic commands ###
