"""Update match and matchdata table

Revision ID: 9fb276fd4ad8
Revises: 14ca3c12162d
Create Date: 2023-12-11 11:30:09.363318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9fb276fd4ad8"
down_revision: Union[str, None] = "14ca3c12162d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "match_date")
    op.add_column(
        "matchdata",
        sa.Column(
            "match_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchdata", "match_date")
    op.add_column(
        "match",
        sa.Column(
            "match_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
