"""Create matches table

Revision ID: 6ae0f074ec19
Revises: 7b7ede01e131
Create Date: 2023-12-10 17:36:19.457814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ae0f074ec19"
down_revision: Union[str, None] = "7b7ede01e131"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("match_eesl_id", sa.Integer(), nullable=True),
        sa.Column("field_length", sa.Integer(), nullable=True),
        sa.Column("match_date", sa.TIME(), nullable=True),
        sa.Column("team_a_id", sa.Integer(), nullable=False),
        sa.Column("team_b_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["team_a_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_b_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournament.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_eesl_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("match")
    # ### end Alembic commands ###
