"""Update scoreboard table

Revision ID: 62c87578ed6a
Revises: 78fc3ba400c0
Create Date: 2023-12-12 12:15:53.403593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62c87578ed6a"
down_revision: Union[str, None] = "78fc3ba400c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scoreboard")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoreboard",
        sa.Column("is_qtr", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_time", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_playclock", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("is_downdistance", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "team_a_color",
            sa.VARCHAR(length=10),
            server_default=sa.text("'#c01c28'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "team_b_color",
            sa.VARCHAR(length=10),
            server_default=sa.text("'#1c71d8'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("match_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name="scoreboard_match_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="scoreboard_pkey"),
        sa.UniqueConstraint("match_id", name="scoreboard_match_id_key"),
    )
    # ### end Alembic commands ###
