"""Update matchdata table

Revision ID: e4885b761d4b
Revises: 6534d4db2d16
Create Date: 2023-12-11 17:30:56.524753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4885b761d4b"
down_revision: Union[str, None] = "6534d4db2d16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matchdata", sa.Column("game_status", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "matchdata", sa.Column("timeout_team_a", sa.String(length=4), nullable=True)
    )
    op.add_column(
        "matchdata", sa.Column("timeout_team_b", sa.String(length=4), nullable=True)
    )
    op.add_column("matchdata", sa.Column("qtr", sa.String(length=10), nullable=True))
    op.add_column("matchdata", sa.Column("gameclock", sa.Integer(), nullable=True))
    op.add_column(
        "matchdata", sa.Column("gameclock_status", sa.String(length=50), nullable=True)
    )
    op.add_column("matchdata", sa.Column("game_clock_task", sa.Text(), nullable=True))
    op.add_column("matchdata", sa.Column("paused_time", sa.Text(), nullable=True))
    op.add_column("matchdata", sa.Column("playclock", sa.Integer(), nullable=True))
    op.add_column(
        "matchdata", sa.Column("playclock_status", sa.String(length=50), nullable=True)
    )
    op.add_column("matchdata", sa.Column("ball_on", sa.Integer(), nullable=True))
    op.add_column("matchdata", sa.Column("down", sa.String(length=10), nullable=True))
    op.add_column(
        "matchdata", sa.Column("distance", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchdata", "distance")
    op.drop_column("matchdata", "down")
    op.drop_column("matchdata", "ball_on")
    op.drop_column("matchdata", "playclock_status")
    op.drop_column("matchdata", "playclock")
    op.drop_column("matchdata", "paused_time")
    op.drop_column("matchdata", "game_clock_task")
    op.drop_column("matchdata", "gameclock_status")
    op.drop_column("matchdata", "gameclock")
    op.drop_column("matchdata", "qtr")
    op.drop_column("matchdata", "timeout_team_b")
    op.drop_column("matchdata", "timeout_team_a")
    op.drop_column("matchdata", "game_status")
    # ### end Alembic commands ###
