"""Update match and matchdata table

Revision ID: afc32b7fa451
Revises: 9fb276fd4ad8
Create Date: 2023-12-11 11:37:08.659091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afc32b7fa451"
down_revision: Union[str, None] = "9fb276fd4ad8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "field_length")
    op.add_column("matchdata", sa.Column("field_length", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchdata", "field_length")
    op.add_column(
        "match",
        sa.Column("field_length", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
