"""Create scoreboard table

Revision ID: 6534d4db2d16
Revises: afc32b7fa451
Create Date: 2023-12-11 16:05:50.543204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6534d4db2d16"
down_revision: Union[str, None] = "afc32b7fa451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoreboard",
        sa.Column("is_qtr", sa.Boolean(), nullable=False),
        sa.Column("is_time", sa.Boolean(), nullable=False),
        sa.Column("is_playclock", sa.Boolean(), nullable=False),
        sa.Column("is_downdistance", sa.Boolean(), nullable=False),
        sa.Column(
            "team_a_color",
            sa.String(length=10),
            server_default="#c01c28",
            nullable=False,
        ),
        sa.Column(
            "team_b_color",
            sa.String(length=10),
            server_default="#1c71d8",
            nullable=False,
        ),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scoreboard")
    # ### end Alembic commands ###
