"""Update scoreboard table

Revision ID: 78fc3ba400c0
Revises: e4885b761d4b
Create Date: 2023-12-12 12:05:07.519664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78fc3ba400c0"
down_revision: Union[str, None] = "e4885b761d4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("scoreboard", "match_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("scoreboard", "match_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
