"""Create matches table

Revision ID: 87bb70e9bbb1
Revises: 74d590a27d8c
Create Date: 2023-12-10 18:09:21.737682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87bb70e9bbb1"
down_revision: Union[str, None] = "74d590a27d8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column(
            "match_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "match_date")
    # ### end Alembic commands ###
