"""sponsor line edited

Revision ID: b7dccbfa8d56
Revises: 4800df71865b
Create Date: 2024-04-06 10:02:49.005664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7dccbfa8d56"
down_revision: Union[str, None] = "4800df71865b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "sponsor_line_tournament_id_fkey", "sponsor_line", type_="foreignkey"
    )
    op.drop_constraint("sponsor_line_team_id_fkey", "sponsor_line", type_="foreignkey")
    op.drop_column("sponsor_line", "tournament_id")
    op.drop_column("sponsor_line", "team_id")
    op.add_column("team", sa.Column("sponsor_line_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "team", "sponsor_line", ["sponsor_line_id"], ["id"])
    op.add_column(
        "tournament", sa.Column("sponsor_line_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "tournament", "sponsor_line", ["sponsor_line_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tournament", type_="foreignkey")
    op.drop_column("tournament", "sponsor_line_id")
    op.drop_constraint(None, "team", type_="foreignkey")
    op.drop_column("team", "sponsor_line_id")
    op.add_column(
        "sponsor_line",
        sa.Column("team_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sponsor_line",
        sa.Column("tournament_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "sponsor_line_team_id_fkey", "sponsor_line", "team", ["team_id"], ["id"]
    )
    op.create_foreign_key(
        "sponsor_line_tournament_id_fkey",
        "sponsor_line",
        "tournament",
        ["tournament_id"],
        ["id"],
    )
    # ### end Alembic commands ###
