"""gameclock table added remainng time

Revision ID: 61817638d713
Revises: 11f5468e9e59
Create Date: 2024-03-17 21:38:11.310564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "61817638d713"
down_revision: Union[str, None] = "11f5468e9e59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gameclock", sa.Column("gameclock_time_remaining", sa.Integer(), nullable=True)
    )
    op.drop_column("gameclock", "start_timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gameclock",
        sa.Column(
            "start_timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("gameclock", "gameclock_time_remaining")
    # ### end Alembic commands ###
