"""refactor match and match_data

Revision ID: ff91e63a5c14
Revises: f6fa1c474f47
Create Date: 2024-01-06 20:11:44.939890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff91e63a5c14"
down_revision: Union[str, None] = "f6fa1c474f47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column(
            "match_date",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_column("matchdata", "paused_time")
    op.drop_column("matchdata", "match_date")
    op.drop_column("matchdata", "game_clock_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matchdata",
        sa.Column("game_clock_task", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "matchdata",
        sa.Column(
            "match_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "matchdata",
        sa.Column("paused_time", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("match", "match_date")
    # ### end Alembic commands ###
