"""player_match model refactored

Revision ID: aff99bfc7bb7
Revises: 6e7222b4d22d
Create Date: 2024-05-17 14:42:13.283218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aff99bfc7bb7"
down_revision: Union[str, None] = "6e7222b4d22d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player_match", sa.Column("team_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "player_match", ["team_id"])
    op.create_foreign_key(
        None, "player_match", "team", ["team_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "player_match", type_="foreignkey")
    op.drop_constraint(None, "player_match", type_="unique")
    op.drop_column("player_match", "team_id")
    # ### end Alembic commands ###
