"""player_match model added

Revision ID: 6e7222b4d22d
Revises: 7b812b434d84
Create Date: 2024-05-16 12:42:27.262234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e7222b4d22d"
down_revision: Union[str, None] = "7b812b434d84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_match",
        sa.Column("player_match_eesl_id", sa.Integer(), nullable=True),
        sa.Column("player_team_tournament_id", sa.Integer(), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column(
            "match_number", sa.String(length=10), server_default="0", nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_team_tournament_id"],
            ["player_team_tournament.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
        sa.UniqueConstraint("player_match_eesl_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_match")
    # ### end Alembic commands ###
