"""add is timeout for scoreboard

Revision ID: b3f51ac3456f
Revises: cededdf0a692
Create Date: 2024-06-21 12:27:31.855327

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3f51ac3456f"
down_revision: Union[str, None] = "cededdf0a692"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard", sa.Column("is_timeout_team_a", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("is_timeout_team_b", sa.Boolean(), nullable=True)
    )
    # Set default value for existing rows
    op.execute(
        "UPDATE scoreboard SET is_timeout_team_a = FALSE WHERE is_timeout_team_a IS NULL"
    )
    op.execute(
        "UPDATE scoreboard SET is_timeout_team_b = FALSE WHERE is_timeout_team_b IS NULL"
    )

    # Alter columns to be non-nullable
    op.alter_column(
        "scoreboard", "is_timeout_team_a", existing_type=sa.Boolean(), nullable=False
    )
    op.alter_column(
        "scoreboard", "is_timeout_team_b", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard", "is_timeout_team_b")
    op.drop_column("scoreboard", "is_timeout_team_a")
    # ### end Alembic commands ###
