"""football events ball picked added

Revision ID: 43c074388d36
Revises: b00a2a20a08d
Create Date: 2024-08-10 16:22:43.175851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43c074388d36"
down_revision: Union[str, None] = "b00a2a20a08d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event", sa.Column("ball_picked_on", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "ball_picked_on")
    # ### end Alembic commands ###
