"""position_id added to player

Revision ID: a1edc9b91430
Revises: 0d0e75703c15
Create Date: 2024-05-06 12:42:21.791351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1edc9b91430"
down_revision: Union[str, None] = "0d0e75703c15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("position_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "player", "position", ["position_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "player", type_="foreignkey")
    op.drop_column("player", "position_id")
    # ### end Alembic commands ###
