"""match sponsors added

Revision ID: 5067c11e0022
Revises: d393ce0d6b54
Create Date: 2024-05-22 15:56:02.830860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5067c11e0022"
down_revision: Union[str, None] = "d393ce0d6b54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard", sa.Column("is_match_sponsor_line", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard", "is_match_sponsor_line")
    # ### end Alembic commands ###
