"""distance on offence added to event

Revision ID: de5256e1fde6
Revises: 2846d8d4a6b4
Create Date: 2024-07-27 12:19:32.960189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de5256e1fde6"
down_revision: Union[str, None] = "2846d8d4a6b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event", sa.Column("distance_on_offence", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "distance_on_offence")
    # ### end Alembic commands ###
