"""positions added

Revision ID: 0d0e75703c15
Revises: 5bfe98ee7834
Create Date: 2024-05-06 12:34:08.899754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d0e75703c15"
down_revision: Union[str, None] = "5bfe98ee7834"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "position",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sport_id"], ["sport.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position")
    # ### end Alembic commands ###
