"""player_match model refactored

Revision ID: 6bfab158561e
Revises: 51f644dfff74
Create Date: 2024-05-17 15:02:08.680309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bfab158561e"
down_revision: Union[str, None] = "51f644dfff74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_match", sa.Column("match_position_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("player_match_position_id_key", "player_match", type_="unique")
    op.create_unique_constraint(None, "player_match", ["match_position_id"])
    op.drop_constraint(
        "player_match_position_id_fkey", "player_match", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "player_match",
        "position",
        ["match_position_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("player_match", "position_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_match",
        sa.Column("position_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "player_match", type_="foreignkey")
    op.create_foreign_key(
        "player_match_position_id_fkey",
        "player_match",
        "position",
        ["position_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint(None, "player_match", type_="unique")
    op.create_unique_constraint(
        "player_match_position_id_key", "player_match", ["position_id"]
    )
    op.drop_column("player_match", "match_position_id")
    # ### end Alembic commands ###
