"""scoreboard is match player lower

Revision ID: 66513fc806b4
Revises: 6f1b4906d140
Create Date: 2024-05-30 17:34:48.408836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66513fc806b4"
down_revision: Union[str, None] = "6f1b4906d140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard", sa.Column("is_match_player_lower", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard", "is_match_player_lower")
    # ### end Alembic commands ###
