"""scoreboard added scale logo

Revision ID: b28de6cd1bc2
Revises: 760b9b433152
Create Date: 2024-03-26 08:18:58.522117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b28de6cd1bc2"
down_revision: Union[str, None] = "760b9b433152"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scoreboard", sa.Column("scale_logo_a", sa.Integer(), nullable=True))
    op.add_column("scoreboard", sa.Column("scale_logo_b", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard", "scale_logo_b")
    op.drop_column("scoreboard", "scale_logo_a")
    # ### end Alembic commands ###
