"""sponsor line edited

Revision ID: f1c02ed30c1c
Revises: b7dccbfa8d56
Create Date: 2024-04-06 10:05:29.149410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1c02ed30c1c"
down_revision: Union[str, None] = "b7dccbfa8d56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("main_sponsor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "team", "sponsor", ["main_sponsor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team", type_="foreignkey")
    op.drop_column("team", "main_sponsor_id")
    # ### end Alembic commands ###
