"""update null to default values

Revision ID: 65d722a5e412
Revises: 6c1e8906d0b6
Create Date: 2024-04-06 11:51:50.766042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "65d722a5e412"
down_revision: Union[str, None] = "6c1e8906d0b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE sponsor SET scale_logo = 1.0 WHERE scale_logo IS NULL")
    op.execute("UPDATE sponsor_sponsor_line SET position = 1 WHERE position IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
