"""gameclock table added timestamp

Revision ID: 11f5468e9e59
Revises: ab72f0659abb
Create Date: 2024-03-17 21:18:16.198314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11f5468e9e59"
down_revision: Union[str, None] = "ab72f0659abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gameclock",
        sa.Column("start_timestamp", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gameclock", "start_timestamp")
    # ### end Alembic commands ###
