"""is teams lower added to scoreboard

Revision ID: cbc23a4c7596
Revises: de5256e1fde6
Create Date: 2024-07-31 11:47:01.267380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cbc23a4c7596"
down_revision: Union[str, None] = "de5256e1fde6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard", sa.Column("is_home_match_team_lower", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("is_away_match_team_lower", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard", "is_away_match_team_lower")
    op.drop_column("scoreboard", "is_home_match_team_lower")
    # ### end Alembic commands ###
