"""add football events

Revision ID: 4f1025627a40
Revises: 20cd0b4c68db
Create Date: 2024-06-29 13:04:08.215337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f1025627a40"
down_revision: Union[str, None] = "20cd0b4c68db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "football_event",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("event_number", sa.Integer(), nullable=True),
        sa.Column("event_qtr", sa.Integer(), nullable=True),
        sa.Column("ball_on", sa.Integer(), nullable=True),
        sa.Column("offense_team", sa.Integer(), nullable=True),
        sa.Column("event_qb", sa.Integer(), nullable=True),
        sa.Column("event_down", sa.String(), nullable=True),
        sa.Column("event_distance", sa.Integer(), nullable=True),
        sa.Column("event_hash", sa.String(), nullable=True),
        sa.Column("play_type", sa.String(), nullable=True),
        sa.Column("play_result", sa.String(), nullable=True),
        sa.Column("run_player", sa.Integer(), nullable=True),
        sa.Column("pass_received_player", sa.Integer(), nullable=True),
        sa.Column("pass_dropped_player", sa.Integer(), nullable=True),
        sa.Column("pass_deflected_player", sa.Integer(), nullable=True),
        sa.Column("pass_intercepted_player", sa.Integer(), nullable=True),
        sa.Column("fumble_player", sa.Integer(), nullable=True),
        sa.Column("fumble_recovered_player", sa.Integer(), nullable=True),
        sa.Column("tackle_player", sa.Integer(), nullable=True),
        sa.Column("sack_player", sa.Integer(), nullable=True),
        sa.Column("kick_player", sa.Integer(), nullable=True),
        sa.Column("punt_player", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_qb"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fumble_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fumble_recovered_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kick_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["offense_team"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pass_deflected_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pass_dropped_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pass_intercepted_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pass_received_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["punt_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sack_player"],
            ["player_match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tackle_player"],
            ["player_match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("football_event")
    # ### end Alembic commands ###
