"""is football qb lower refactored to scoreboard

Revision ID: 86d684ac343b
Revises: 7c2c94c4237a
Create Date: 2024-08-01 13:18:08.495009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86d684ac343b"
down_revision: Union[str, None] = "7c2c94c4237a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard",
        sa.Column("football_qb_full_stats_match_lower_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "scoreboard",
        "player_match",
        ["football_qb_full_stats_match_lower_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scoreboard", type_="foreignkey")
    op.drop_column("scoreboard", "football_qb_full_stats_match_lower_id")
    # ### end Alembic commands ###
