"""team and scorebored table reformat

Revision ID: 4b3cce5a35bc
Revises: 61817638d713
Create Date: 2024-03-18 15:30:33.218733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b3cce5a35bc"
down_revision: Union[str, None] = "61817638d713"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard",
        sa.Column(
            "team_a_game_color",
            sa.String(length=10),
            server_default="#c01c28",
            nullable=False,
        ),
    )
    op.add_column(
        "scoreboard", sa.Column("use_team_a_game_color", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard",
        sa.Column(
            "team_b_game_color",
            sa.String(length=10),
            server_default="#1c71d8",
            nullable=False,
        ),
    )
    op.add_column(
        "scoreboard", sa.Column("use_team_b_game_color", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("team_a_game_title", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("use_team_a_game_title", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("team_b_game_title", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("use_team_b_game_title", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("team_a_game_logo", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("use_team_a_game_logo", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("team_b_game_logo", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("use_team_b_game_logo", sa.Boolean(), nullable=True)
    )
    op.drop_column("scoreboard", "team_b_color")
    op.drop_column("scoreboard", "team_a_color")
    op.add_column(
        "team",
        sa.Column(
            "team_color", sa.String(length=10), server_default="#c01c28", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "team_color")
    op.add_column(
        "scoreboard",
        sa.Column(
            "team_a_color",
            sa.VARCHAR(length=10),
            server_default=sa.text("'#c01c28'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "scoreboard",
        sa.Column(
            "team_b_color",
            sa.VARCHAR(length=10),
            server_default=sa.text("'#1c71d8'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("scoreboard", "use_team_b_game_logo")
    op.drop_column("scoreboard", "team_b_game_logo")
    op.drop_column("scoreboard", "use_team_a_game_logo")
    op.drop_column("scoreboard", "team_a_game_logo")
    op.drop_column("scoreboard", "use_team_b_game_title")
    op.drop_column("scoreboard", "team_b_game_title")
    op.drop_column("scoreboard", "use_team_a_game_title")
    op.drop_column("scoreboard", "team_a_game_title")
    op.drop_column("scoreboard", "use_team_b_game_color")
    op.drop_column("scoreboard", "team_b_game_color")
    op.drop_column("scoreboard", "use_team_a_game_color")
    op.drop_column("scoreboard", "team_a_game_color")
    # ### end Alembic commands ###
