"""fooball events refactor

Revision ID: 66a2c03c4088
Revises: 4f1025627a40
Create Date: 2024-06-29 13:17:54.460567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66a2c03c4088"
down_revision: Union[str, None] = "4f1025627a40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "event_down")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event",
        sa.Column("event_down", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
