"""sponsor sponsor line connection edited

Revision ID: 6c1e8906d0b6
Revises: da023b0e761e
Create Date: 2024-04-06 11:46:18.322997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c1e8906d0b6"
down_revision: Union[str, None] = "da023b0e761e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsor", sa.Column("scale_logo", sa.Float(), nullable=True))
    op.add_column(
        "sponsor_sponsor_line",
        sa.Column("position", sa.Integer(), server_default="1", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsor_sponsor_line", "position")
    op.drop_column("sponsor", "scale_logo")
    # ### end Alembic commands ###
