"""football event picked on fumble added

Revision ID: 2cf1902c7d5c
Revises: d3f704587842
Create Date: 2024-08-13 10:21:47.921285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cf1902c7d5c"
down_revision: Union[str, None] = "d3f704587842"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event", sa.Column("ball_picked_on_fumble", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "ball_picked_on_fumble")
    # ### end Alembic commands ###
