"""scoreboard toggle rosters

Revision ID: 6f1b4906d140
Revises: 2764af5116ed
Create Date: 2024-05-28 16:45:02.993241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f1b4906d140"
down_revision: Union[str, None] = "2764af5116ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard", sa.Column("is_team_a_start_offense", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("is_team_b_start_offense", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("is_team_a_start_defense", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "scoreboard", sa.Column("is_team_b_start_defense", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scoreboard", "is_team_b_start_defense")
    op.drop_column("scoreboard", "is_team_a_start_defense")
    op.drop_column("scoreboard", "is_team_b_start_offense")
    op.drop_column("scoreboard", "is_team_a_start_offense")
    # ### end Alembic commands ###
