"""gameclock max

Revision ID: 2846d8d4a6b4
Revises: 19d0e91b6c53
Create Date: 2024-07-24 12:45:59.368270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2846d8d4a6b4"
down_revision: Union[str, None] = "19d0e91b6c53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("gameclock", sa.Column("gameclock_max", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gameclock", "gameclock_max")
    # ### end Alembic commands ###
