"""football events fumble

Revision ID: cc5bc20be543
Revises: c86b1c31d21d
Create Date: 2024-07-21 14:22:49.693318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc5bc20be543"
down_revision: Union[str, None] = "c86b1c31d21d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event", sa.Column("play_direction", sa.String(), nullable=True)
    )
    op.add_column("football_event", sa.Column("is_fumble", sa.Boolean(), nullable=True))
    op.add_column(
        "football_event", sa.Column("is_fumble_recovered", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "is_fumble_recovered")
    op.drop_column("football_event", "is_fumble")
    op.drop_column("football_event", "play_direction")
    # ### end Alembic commands ###
