"""player_match model refactored

Revision ID: 51f644dfff74
Revises: aff99bfc7bb7
Create Date: 2024-05-17 14:51:04.584740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51f644dfff74"
down_revision: Union[str, None] = "aff99bfc7bb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player_match", sa.Column("position_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "player_match", ["position_id"])
    op.drop_constraint(
        "player_match_player_team_tournament_id_fkey", "player_match", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "player_match",
        "player_team_tournament",
        ["player_team_tournament_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "player_match", "position", ["position_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "player_match", type_="foreignkey")
    op.drop_constraint(None, "player_match", type_="foreignkey")
    op.create_foreign_key(
        "player_match_player_team_tournament_id_fkey",
        "player_match",
        "player_team_tournament",
        ["player_team_tournament_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "player_match", type_="unique")
    op.drop_column("player_match", "position_id")
    # ### end Alembic commands ###
