"""person dob

Revision ID: 2ad83031f5de
Revises: 62c11d7db0f9
Create Date: 2024-04-29 12:08:33.011051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ad83031f5de"
down_revision: Union[str, None] = "62c11d7db0f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person", sa.Column("person_dob", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_column("person", "match_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person",
        sa.Column(
            "match_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("person", "person_dob")
    # ### end Alembic commands ###
