"""football event ball moved to attribute

Revision ID: c5b2b95b0153
Revises: b2f4516ce665
Create Date: 2024-08-07 16:54:57.728879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c5b2b95b0153"
down_revision: Union[str, None] = "b2f4516ce665"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event", sa.Column("ball_moved_to", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "ball_moved_to")
    # ### end Alembic commands ###
