"""match table updated with week

Revision ID: 99b8550ebf7a
Revises: f5cc39d76e3c
Create Date: 2024-01-19 23:57:52.790931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99b8550ebf7a"
down_revision: Union[str, None] = "f5cc39d76e3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("week", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "week")
    # ### end Alembic commands ###
