"""player eesl_id

Revision ID: 16900df02f8a
Revises: 09da569e356c
Create Date: 2024-04-29 12:33:59.981484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16900df02f8a"
down_revision: Union[str, None] = "09da569e356c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("player_eesl_id", sa.Integer(), nullable=True))
    op.drop_constraint("player_eesl_id_key", "player", type_="unique")
    op.create_unique_constraint(None, "player", ["player_eesl_id"])
    op.drop_column("player", "eesl_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player", sa.Column("eesl_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "player", type_="unique")
    op.create_unique_constraint("player_eesl_id_key", "player", ["eesl_id"])
    op.drop_column("player", "player_eesl_id")
    # ### end Alembic commands ###
