"""person, player and player_team_tournamen added

Revision ID: 62c11d7db0f9
Revises: 36cab58beaa4
Create Date: 2024-04-29 12:02:46.875464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62c11d7db0f9"
down_revision: Union[str, None] = "36cab58beaa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person",
        sa.Column(
            "first_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "second_name", sa.String(length=100), server_default="", nullable=False
        ),
        sa.Column(
            "person_photo_url", sa.String(length=500), server_default="", nullable=True
        ),
        sa.Column("match_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "player",
        sa.Column("sport_id", sa.Integer(), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("eesl_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sport_id"], ["sport.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("eesl_id"),
    )
    op.create_table(
        "player_team_tournament",
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("tournament_id", sa.Integer(), nullable=True),
        sa.Column(
            "player_number", sa.String(length=10), server_default="0", nullable=True
        ),
        sa.Column(
            "player_position", sa.String(length=20), server_default="", nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournament.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "team",
        "team_logo_url",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "team",
        "team_logo_url",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_table("player_team_tournament")
    op.drop_table("player")
    op.drop_table("person")
    # ### end Alembic commands ###
