"""match sponsors added

Revision ID: d393ce0d6b54
Revises: 891ef69dd524
Create Date: 2024-05-22 15:11:18.719841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d393ce0d6b54"
down_revision: Union[str, None] = "891ef69dd524"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("main_sponsor_id", sa.Integer(), nullable=True))
    op.add_column("match", sa.Column("sponsor_line_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "match", "sponsor_line", ["sponsor_line_id"], ["id"])
    op.create_foreign_key(None, "match", "sponsor", ["main_sponsor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_column("match", "sponsor_line_id")
    op.drop_column("match", "main_sponsor_id")
    # ### end Alembic commands ###
