"""team table added sport_id

Revision ID: b99c51e3b2b8
Revises: 99b8550ebf7a
Create Date: 2024-01-20 10:49:37.167166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b99c51e3b2b8"
down_revision: Union[str, None] = "99b8550ebf7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team", sa.Column("sport_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "team", ["sport_id"])
    op.create_foreign_key(
        None, "team", "sport", ["sport_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team", type_="foreignkey")
    op.drop_constraint(None, "team", type_="unique")
    op.drop_column("team", "sport_id")
    # ### end Alembic commands ###
