"""football events ball kicked and returned to added

Revision ID: b00a2a20a08d
Revises: c5b2b95b0153
Create Date: 2024-08-10 10:28:37.829015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b00a2a20a08d"
down_revision: Union[str, None] = "c5b2b95b0153"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event", sa.Column("ball_kicked_to", sa.Integer(), nullable=True)
    )
    op.add_column(
        "football_event", sa.Column("ball_returned_to", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "ball_returned_to")
    op.drop_column("football_event", "ball_kicked_to")
    # ### end Alembic commands ###
