"""position_id added to player

Revision ID: a5cc1e73b628
Revises: a1edc9b91430
Create Date: 2024-05-06 12:45:50.045387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a5cc1e73b628"
down_revision: Union[str, None] = "a1edc9b91430"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("player_position_id_fkey", "player", type_="foreignkey")
    op.drop_column("player", "position_id")
    op.add_column(
        "player_team_tournament", sa.Column("position_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "player_team_tournament",
        "position",
        ["position_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("player_team_tournament", "player_position")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_team_tournament",
        sa.Column(
            "player_position",
            sa.VARCHAR(length=20),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "player_team_tournament", type_="foreignkey")
    op.drop_column("player_team_tournament", "position_id")
    op.add_column(
        "player",
        sa.Column("position_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "player_position_id_fkey",
        "player",
        "position",
        ["position_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
