"""sponsor sponsor line connection added

Revision ID: da023b0e761e
Revises: f1c02ed30c1c
Create Date: 2024-04-06 10:35:44.832914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da023b0e761e"
down_revision: Union[str, None] = "f1c02ed30c1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsor_sponsor_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sponsor_line_id", sa.Integer(), nullable=False),
        sa.Column("sponsor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["sponsor_id"], ["sponsor.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sponsor_line_id"], ["sponsor_line.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sponsor_line_id", "sponsor_id", name="idx_unique_sponsor_sponsor_line"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sponsor_sponsor_line")
    # ### end Alembic commands ###
