"""team_timout nullable

Revision ID: 20cd0b4c68db
Revises: b3f51ac3456f
Create Date: 2024-06-29 13:02:47.613879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20cd0b4c68db"
down_revision: Union[str, None] = "b3f51ac3456f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scoreboard", "is_timeout_team_a", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "scoreboard", "is_timeout_team_b", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scoreboard", "is_timeout_team_b", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "scoreboard", "is_timeout_team_a", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
