"""matchdata removed gameclock

Revision ID: 36cab58beaa4
Revises: fc865adb8983
Create Date: 2024-04-26 12:48:07.185473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36cab58beaa4"
down_revision: Union[str, None] = "fc865adb8983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchdata", "gameclock_status")
    op.drop_column("matchdata", "gameclock")
    op.alter_column(
        "scoreboard",
        "scale_tournament_logo",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'2'::double precision"),
    )
    op.alter_column(
        "scoreboard",
        "scale_main_sponsor",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'2'::double precision"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scoreboard",
        "scale_main_sponsor",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'2'::double precision"),
    )
    op.alter_column(
        "scoreboard",
        "scale_tournament_logo",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'2'::double precision"),
    )
    op.add_column(
        "matchdata",
        sa.Column("gameclock", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "matchdata",
        sa.Column(
            "gameclock_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
