"""gameclock table and model added

Revision ID: 777f9cc33163
Revises: 38655a4ba8f7
Create Date: 2024-03-17 16:56:04.630753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "777f9cc33163"
down_revision: Union[str, None] = "38655a4ba8f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gameclock",
        sa.Column("gameclock", sa.Integer(), nullable=True),
        sa.Column("gameclock_status", sa.String(length=50), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gameclock")
    # ### end Alembic commands ###
