"""playclock table created

Revision ID: 3de595f1e2d9
Revises: 5d7a5e992574
Create Date: 2024-03-14 11:43:29.042249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3de595f1e2d9"
down_revision: Union[str, None] = "5d7a5e992574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playclock",
        sa.Column("playclock", sa.Integer(), nullable=True),
        sa.Column("playclock_status", sa.String(length=50), nullable=True),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playclock")
    # ### end Alembic commands ###
