"""position ondelete refactored

Revision ID: 7b812b434d84
Revises: a5cc1e73b628
Create Date: 2024-05-06 12:57:47.097345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b812b434d84"
down_revision: Union[str, None] = "a5cc1e73b628"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "player_team_tournament_position_id_fkey",
        "player_team_tournament",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "player_team_tournament",
        "position",
        ["position_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "player_team_tournament", type_="foreignkey")
    op.create_foreign_key(
        "player_team_tournament_position_id_fkey",
        "player_team_tournament",
        "position",
        ["position_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
