"""football event return to on fumble added

Revision ID: d3f704587842
Revises: 4972025f2649
Create Date: 2024-08-13 10:09:03.441621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3f704587842"
down_revision: Union[str, None] = "4972025f2649"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "football_event",
        sa.Column("ball_returned_to_on_fumble", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("football_event", "ball_returned_to_on_fumble")
    # ### end Alembic commands ###
