"""person resize uploaded images

Revision ID: 67c31862b867
Revises: cb048424352e
Create Date: 2024-05-03 22:45:04.380110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67c31862b867"
down_revision: Union[str, None] = "cb048424352e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person",
        sa.Column(
            "person_photo_icon_url",
            sa.String(length=500),
            server_default="",
            nullable=True,
        ),
    )
    op.add_column(
        "person",
        sa.Column(
            "person_photo_web_url",
            sa.String(length=500),
            server_default="",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "person_photo_web_url")
    op.drop_column("person", "person_photo_icon_url")
    # ### end Alembic commands ###
