"""is football qb lower refactored to scoreboard

Revision ID: 7c2c94c4237a
Revises: e0ec44347ec5
Create Date: 2024-08-01 12:43:28.903325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c2c94c4237a"
down_revision: Union[str, None] = "e0ec44347ec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard",
        sa.Column("is_football_qb_full_stats_lower", sa.Boolean(), nullable=True),
    )
    op.drop_column("scoreboard", "is_away_football_qb_lower")
    op.drop_column("scoreboard", "is_home_football_qb_lower")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scoreboard",
        sa.Column(
            "is_home_football_qb_lower", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "scoreboard",
        sa.Column(
            "is_away_football_qb_lower", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("scoreboard", "is_football_qb_full_stats_lower")
    # ### end Alembic commands ###
