"""sponsor line visibe

Revision ID: f2270d185c2d
Revises: 65d722a5e412
Create Date: 2024-04-06 12:19:23.426856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f2270d185c2d"
down_revision: Union[str, None] = "65d722a5e412"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sponsor_line", sa.Column("is_visible", sa.Boolean(), nullable=True))
    op.execute("UPDATE sponsor_line SET is_visible = FALSE WHERE is_visible IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sponsor_line", "is_visible")
    # ### end Alembic commands ###
