"""sponsors to tournament added

Revision ID: f7e518a5dbf2
Revises: 28e0510f3288
Create Date: 2024-04-05 09:18:37.037193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7e518a5dbf2"
down_revision: Union[str, None] = "28e0510f3288"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sponsor",
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("logo_url", sa.String(length=255), server_default="", nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "tournament", sa.Column("main_sponsor_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "tournament", "sponsor", ["main_sponsor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tournament", type_="foreignkey")
    op.drop_column("tournament", "main_sponsor_id")
    op.drop_table("sponsor")
    # ### end Alembic commands ###
