"""team resize uploaded images

Revision ID: d0338dce74c0
Revises: 67c31862b867
Create Date: 2024-05-04 10:56:37.891314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0338dce74c0"
down_revision: Union[str, None] = "67c31862b867"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team",
        sa.Column(
            "team_logo_icon_url", sa.String(length=500), server_default="", nullable=True
        ),
    )
    op.add_column(
        "team",
        sa.Column(
            "team_logo_web_url", sa.String(length=500), server_default="", nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team", "team_logo_web_url")
    op.drop_column("team", "team_logo_icon_url")
    # ### end Alembic commands ###
