"""playclock removed from matchdata

Revision ID: 38655a4ba8f7
Revises: e154049af71c
Create Date: 2024-03-17 14:09:32.263796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38655a4ba8f7"
down_revision: Union[str, None] = "e154049af71c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matchdata", "playclock_status")
    op.drop_column("matchdata", "playclock")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matchdata",
        sa.Column("playclock", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "matchdata",
        sa.Column(
            "playclock_status", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
