"""add_users_roles_tables

Revision ID: 752e65b4a9a0
Revises: 2b75ce6c136d
Create Date: 2026-01-04 12:09:30.692258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "752e65b4a9a0"
down_revision: Union[str, None] = "2b75ce6c136d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["person_id"], ["person.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.drop_index("ix_football_event_match_id", table_name="football_event")
    op.drop_index("ix_match_tournament_id_team_a_id_team_b_id", table_name="match")
    op.drop_index("ix_player_match_match_id_player_match_eesl_id", table_name="player_match")
    op.drop_index(
        "ix_player_team_tournament_tournament_id_player_id", table_name="player_team_tournament"
    )
    op.drop_index("ix_scoreboard_match_id_player_match_lower_id", table_name="scoreboard")
    op.alter_column("tournament", "sport_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tournament", "sport_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        "ix_scoreboard_match_id_player_match_lower_id",
        "scoreboard",
        ["match_id", "player_match_lower_id"],
        unique=False,
    )
    op.create_index(
        "ix_player_team_tournament_tournament_id_player_id",
        "player_team_tournament",
        ["tournament_id", "player_id"],
        unique=False,
    )
    op.create_index(
        "ix_player_match_match_id_player_match_eesl_id",
        "player_match",
        ["match_id", "player_match_eesl_id"],
        unique=False,
    )
    op.create_index(
        "ix_match_tournament_id_team_a_id_team_b_id",
        "match",
        ["tournament_id", "team_a_id", "team_b_id"],
        unique=False,
    )
    op.create_index("ix_football_event_match_id", "football_event", ["match_id"], unique=False)
    op.drop_table("user_role")
    op.drop_table("user")
    op.drop_table("role")
    # ### end Alembic commands ###
