"""add user ownership and isprivate columns to tournament, player, person, match, team models

Revision ID: 5fc3e8f9a8f1
Revises: 935b31e992ed
Create Date: 2026-01-15 14:35:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fc3e8f9a8f1"
down_revision: Union[str, None] = "935b31e992ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column(
        "match", sa.Column("isprivate", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_foreign_key(
        "fk_match_user", "match", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("person", sa.Column("owner_user_id", sa.Integer(), nullable=True))
    op.add_column(
        "person", sa.Column("isprivate", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_foreign_key(
        "fk_person_owner_user", "person", "user", ["owner_user_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("player", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column(
        "player", sa.Column("isprivate", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_foreign_key(
        "fk_player_user", "player", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("team", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column(
        "team", sa.Column("isprivate", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_foreign_key("fk_team_user", "team", "user", ["user_id"], ["id"], ondelete="SET NULL")
    op.add_column("tournament", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column(
        "tournament", sa.Column("isprivate", sa.Boolean(), server_default="false", nullable=False)
    )
    op.create_foreign_key(
        "fk_tournament_user", "tournament", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tournament_user", "tournament", type_="foreignkey")
    op.drop_column("tournament", "isprivate")
    op.drop_column("tournament", "user_id")
    op.drop_constraint("fk_team_user", "team", type_="foreignkey")
    op.drop_column("team", "isprivate")
    op.drop_column("team", "user_id")
    op.drop_constraint("fk_player_user", "player", type_="foreignkey")
    op.drop_column("player", "isprivate")
    op.drop_column("player", "user_id")
    op.drop_constraint("fk_person_owner_user", "person", type_="foreignkey")
    op.drop_column("person", "isprivate")
    op.drop_column("person", "owner_user_id")
    op.drop_constraint("fk_match_user", "match", type_="foreignkey")
    op.drop_column("match", "isprivate")
    op.drop_column("match", "user_id")
    # ### end Alembic commands ###
