"""Add created, last_online, is_online to user table

Revision ID: 82444823b344
Revises: a5855ca979f4
Create Date: 2026-01-19 17:21:39.219986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82444823b344"
down_revision: Union[str, None] = "a5855ca979f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("last_online", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "user", sa.Column("is_online", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "user",
        sa.Column(
            "created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_online")
    op.drop_column("user", "last_online")
    op.drop_column("user", "created")
    # ### end Alembic commands ###
