"""add iscurrent field to season model

Revision ID: 935b31e992ed
Revises: 8f4e3c9d7e5
Create Date: 2026-01-15 13:58:10.382036

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "935b31e992ed"
down_revision: Union[str, None] = "32e4ddf548e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_person_first_name_gin_trgm")
    op.execute("DROP INDEX IF EXISTS ix_person_first_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_person_search_vector")
    op.execute("DROP INDEX IF EXISTS ix_person_second_name_gin_trgm")
    op.execute("DROP INDEX IF EXISTS ix_person_second_name_trgm")
    op.execute("ALTER TABLE person DROP COLUMN IF EXISTS search_vector")
    op.execute("DROP INDEX IF EXISTS ix_player_team_tournament_search_vector")
    op.execute("ALTER TABLE player_team_tournament DROP COLUMN IF EXISTS search_vector")
    op.add_column(
        "season", sa.Column("iscurrent", sa.Boolean(), server_default="false", nullable=True)
    )
    op.execute("DROP INDEX IF EXISTS ix_team_search_vector")
    op.execute("DROP INDEX IF EXISTS ix_team_title_trgm")
    op.execute("ALTER TABLE team DROP COLUMN IF EXISTS search_vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team",
        sa.Column("search_vector", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_team_title_trgm", "team", ["title"], unique=False, postgresql_using="gin")
    op.create_index(
        "ix_team_search_vector", "team", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.drop_column("season", "iscurrent")
    op.add_column(
        "player_team_tournament",
        sa.Column("search_vector", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_player_team_tournament_search_vector",
        "player_team_tournament",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "person",
        sa.Column("search_vector", postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_person_second_name_trgm",
        "person",
        ["second_name"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_person_second_name_gin_trgm",
        "person",
        ["second_name"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_person_search_vector", "person", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_person_first_name_trgm", "person", ["first_name"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_person_first_name_gin_trgm",
        "person",
        ["first_name"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###
