"""Add global_setting table

Revision ID: c35330967b94
Revises: 82444823b344
Create Date: 2026-01-19 22:53:43.133396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35330967b94'
down_revision: Union[str, None] = '82444823b344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('value_type', sa.String(length=20), server_default='string', nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_setting')
    # ### end Alembic commands ###
