"""add started_at_ms to playclock

Revision ID: ab510d625072
Revises: 50f87cfd5ce4
Create Date: 2026-01-24 10:38:49.909647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab510d625072'
down_revision: Union[str, None] = '50f87cfd5ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playclock', sa.Column('started_at_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playclock', 'started_at_ms')
    # ### end Alembic commands ###
