version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s - Class: %(classname)s - Func: %(funcName)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout  # Direct logs to standard output (console)
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: backend.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
filters:
  context_filter:
    (): src.logging_config.ContextFilter
loggers:
  backend_logger_fastapi:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  backend_logger_server:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_config:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_base_db:
    level: DEBUG
    handlers: [ console, file ]
    filters: [context_filter]
    propagate: no
  backend_logger_helpers:
    level: ERROR
    handlers: [ console, file ]
    propagate: no
  backend_fetch_data_helpers:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_parser_eesl:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_fileservice:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_WebSocketManager:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  backend_websocket_logger:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

  backend_connection_socket_logger:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

  backend_logger_SeasonServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_SportServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_TournamentServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_TeamServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_TeamTournamentServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_MatchServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_MatchDataServiceDB:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no


  backend_logger_SportAPIRouter:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_TournamentAPIRouter:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_TeamAPIRouter:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_MatchAPIRouter:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
root:
  level: WARNING
  handlers: [console]
