version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout  # Direct logs to standard output (console)
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: backend.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
loggers:
  backend_logger_fastapi:
    level: WARNING
    handlers: [console, file]
    propagate: no
  backend_logger_server:
    level: WARNING
    handlers: [ console, file ]
    propagate: no
  backend_logger_config:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_base_db:
    level: WARNING
    handlers: [ console, file ]
    propagate: no
  backend_logger_helpers:
    level: ERROR
    handlers: [ console, file ]
    propagate: no
  backend_fetch_data_helpers:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
  backend_logger_WebSocketManager:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  backend_websocket_logger:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

  backend_connection_socket_logger:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no

  backend_logger_MatchServiceDB:
    level: WARNING
    handlers: [ console, file ]
    propagate: no
  backend_logger_MatchDataServiceDB:
    level: WARNING
    handlers: [ console, file ]
    propagate: no
root:
  level: WARNING
  handlers: [console]
