version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout  # Direct logs to standard output (console)
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
#    filename: src/logs/backend.log  # Save logs to backend-specific file
    filename: backend.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
loggers:
  backend_logger_fastapi:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  backend_logger_server:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
root:
  level: WARNING
  handlers: [console]
