name: Cleanup Workflow

on:
  workflow_run:
    workflows: ["Deploy"] 
    types:
      - completed

jobs:
  cleanup:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup Temp Files or Resources
      run: |
        echo "Cleaning up temporary resources..."
        # Add any commands to clean up after the deployment
        rm -rf /tmp/*  # Example cleanup

    - name: Cleanup SSH Keys
      run: |
        echo "Cleaning up SSH keys..."
        rm -rf ~/.ssh  # Clean up SSH keys
