name: Cleanup Workflow

on:
  workflow_run:
    workflows: ["Deploy"] 
    types:
      - completed

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup SSH Keys
      run: |
        echo "Cleaning up SSH keys..."
        rm -rf ~/.ssh  # Clean up SSH keys
